export type Database = {
  public: {
    Tables: {
      profiles: { Row: { id: string; full_name: string | null; avatar_url: string | null; created_at: string; updated_at: string }; Insert: Partial<Database['public']['Tables']['profiles']['Row']> & { id: string }; Update: Partial<Database['public']['Tables']['profiles']['Row']> }
      workspaces: { Row: { id: string; owner_id: string; name: string; slug: string; timezone: string; logo_url: string | null; plan: 'Hook' | 'Solo' | 'Agency'; created_at: string }; Insert: Omit<Database['public']['Tables']['workspaces']['Row'], 'id' | 'created_at'> & Partial<Pick<Database['public']['Tables']['workspaces']['Row'], 'id' | 'created_at'>>; Update: Partial<Database['public']['Tables']['workspaces']['Row']> }
      workspace_members: { Row: { workspace_id: string; user_id: string; role: 'owner' | 'admin' | 'member'; created_at: string }; Insert: Omit<Database['public']['Tables']['workspace_members']['Row'], 'created_at'> & Partial<Pick<Database['public']['Tables']['workspace_members']['Row'], 'created_at'>>; Update: Partial<Database['public']['Tables']['workspace_members']['Row']> }
      invoices: { Row: { id: string; workspace_id: string; client_name: string; client_email: string; amount: number; currency: string; due_date: string; status: 'pending' | 'paid' | 'paused' | 'disputed'; ai_status: 'nudge_sent' | 'escalated' | 'pending' | 'paid'; last_chased_at: string | null; reminder_count: number; created_at: string }; Insert: Omit<Database['public']['Tables']['invoices']['Row'], 'id' | 'created_at' | 'ai_status' | 'last_chased_at' | 'reminder_count'> & Partial<Pick<Database['public']['Tables']['invoices']['Row'], 'id' | 'created_at' | 'ai_status' | 'last_chased_at' | 'reminder_count'>>; Update: Partial<Database['public']['Tables']['invoices']['Row']> }
      gateway_settings: { Row: { id: string; workspace_id: string; type: 'stripe' | 'razorpay' | 'upi' | 'custom'; label: string; api_key: string | null; static_url: string | null; is_active: boolean; created_at: string }; Insert: Omit<Database['public']['Tables']['gateway_settings']['Row'], 'id' | 'created_at'> & Partial<Pick<Database['public']['Tables']['gateway_settings']['Row'], 'id' | 'created_at'>>; Update: Partial<Database['public']['Tables']['gateway_settings']['Row']> }
      tone_settings: { Row: { workspace_id: string; sample_emails: string; tone_level: number; ai_prompt: string; updated_at: string }; Insert: Omit<Database['public']['Tables']['tone_settings']['Row'], 'updated_at'> & Partial<Pick<Database['public']['Tables']['tone_settings']['Row'], 'updated_at'>>; Update: Partial<Database['public']['Tables']['tone_settings']['Row']> }
      activity_items: { Row: { id: string; workspace_id: string; type: string; message: string; amount: number | null; created_at: string }; Insert: Omit<Database['public']['Tables']['activity_items']['Row'], 'id' | 'created_at'> & Partial<Pick<Database['public']['Tables']['activity_items']['Row'], 'id' | 'created_at'>>; Update: Partial<Database['public']['Tables']['activity_items']['Row']> }
    }
  }
}
